#!/usr/bin/env bash
# #81: wrapper łączący pipeline agenta krypto — fetch (#78) → analiza (#79) →
# sync wartości konta z OKX (#87) → decyzja agenta (#80, Claude/Codex headless)
# — jedno wywołanie z crona co 15 min.
#
# Użycie (crontab -e), przekierowanie stdout do /dev/null bo skrypt sam
# dopisuje do LOG_FILE przez `tee` (żeby to samo było widoczne na ekranie
# przy ręcznym uruchomieniu, bez podwójnego zapisu z crona):
#   */15 * * * * /home/corozya/www/crypto-trading-agent/scripts/run_agent_krypto_cycle.sh >> /dev/null 2>&1
# Ręcznie z dodatkową instrukcją i wybranym providerem:
#   /home/corozya/www/crypto-trading-agent/scripts/run_agent_krypto_cycle.sh --provider codex --interactive
#
# Logowanie: każde uruchomienie wypisuje na stdout ORAZ dopisuje do LOG_FILE
# (poniżej) z timestampem, statusem każdego kroku (fetch/analyze/decision) i
# pełnym surowym outputem — pozwala zdiagnozować pipeline bez czekania na
# kolejny cykl (na żywo przy ręcznym uruchomieniu, albo w pliku przy cronie).
# Dodatkowo #83:
# scripts/agent_krypto_decisions.jsonl — jedna linia JSON per cykl z samymi
# decyzjami (WAIT/TRADE per symbol, reason, koszt) wyciągniętymi z odpowiedzi
# agenta, do szybkiego przeglądu bez grzebania w surowym logu technicznym.
#
# Idempotency: CYCLE_ID jest stabilny dla okna 15-minutowego. Retry procesu w
# tym samym oknie przekazuje agentowi ten sam bazowy klucz. Pełna ochrona
# wymaga również trwałego journala w backendzie; sam klucz w promptcie nie jest
# wystarczającą gwarancją po niejednoznacznym timeout.
#
# Obsługa błędu: `set -o pipefail` + explicit exit code check po każdym kroku
# — fetch/analyze fail nie wstrzymuje pipeline'u w nieskończoność (timeout na
# invoke agenta), tylko loguje i kończy ten cykl z niezerowym exit code.
set -uo pipefail

usage() {
    cat <<'EOF'
Użycie: run_agent_krypto_cycle.sh [--provider claude|codex|alternate] [--interactive]

Opcje:
  --provider P   Provider modelu: claude, codex albo alternate.
                 Domyślnie: AGENT_KRYPTO_PROVIDER lub claude.
  --interactive  Przed decyzją agenta zapytaj o dodatkową treść do promptu.
  -h, --help     Pokaż tę pomoc i zakończ.

Bez --interactive skrypt nie czyta stdin i działa jak dotychczas.
EOF
}

INTERACTIVE=false
PROVIDER="${AGENT_KRYPTO_PROVIDER:-claude}"
while [ "$#" -gt 0 ]; do
    case "$1" in
        --provider)
            if [ "$#" -lt 2 ]; then
                printf 'Błąd: --provider wymaga wartości.\n\n' >&2
                usage >&2
                exit 2
            fi
            PROVIDER="$2"
            shift
            ;;
        --provider=*)
            PROVIDER="${1#*=}"
            ;;
        --interactive)
            INTERACTIVE=true
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            printf 'Błąd: nieznany argument: %s\n\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

case "$PROVIDER" in
    claude|codex|alternate) ;;
    *)
        printf 'Błąd: nieznany provider: %s (dozwolone: claude, codex, alternate)\n' "$PROVIDER" >&2
        exit 2
        ;;
esac

# Nadpisywanie ścieżek jest używane przez test integracyjny do podstawienia
# lokalnych atrap. Standardowe uruchomienie jest samodzielne.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${AGENT_KRYPTO_REPO_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"
BACKEND="$REPO_ROOT/backend"
PYTHON="${PYTHON:-$REPO_ROOT/.venv/bin/python}"
RUNTIME_ROOT="${CRYPTO_RUNTIME_ROOT:-$REPO_ROOT/data/runtime}"
LOG_FILE="$RUNTIME_ROOT/logs/agent_krypto_cron.log"
# Runtime-owned config: unlike .mcp.agent-krypto.json it is not generated by
# SAURON onboarding, więc kolejny onboarding nie może usunąć portfolio-tracker.
MCP_CONFIG="${AGENT_KRYPTO_CLAUDE_MCP_CONFIG:-$REPO_ROOT/scripts/agent_krypto_claude.mcp.json}"
MCP_CONFIG_VALIDATOR="$REPO_ROOT/scripts/validate_agent_krypto_mcp_config.py"
CODEX_PROFILE_VALIDATOR="$REPO_ROOT/scripts/validate_agent_krypto_codex_profile.py"
PREFLIGHT_PYTHON="${AGENT_KRYPTO_PREFLIGHT_PYTHON:-/usr/bin/python3}"
REPORT_SCHEMA="$REPO_ROOT/scripts/agent_krypto_report.schema.json"
REPORT_VALIDATOR="$REPO_ROOT/scripts/validate_agent_krypto_report.py"
SNAPSHOT_PREPARER="$REPO_ROOT/scripts/prepare_agent_krypto_snapshots.py"
SNAPSHOT_DIR="${AGENT_KRYPTO_SNAPSHOT_DIR:-$RUNTIME_ROOT/snapshots/crypto_market}"
SNAPSHOT_MAX_AGE_SECONDS="${AGENT_KRYPTO_SNAPSHOT_MAX_AGE_SECONDS:-1200}"
LOCK_FILE="${AGENT_KRYPTO_LOCK_FILE:-$RUNTIME_ROOT/agent_krypto_cycle.lock}"
AUTOTRADER_STATE_FILE="${BTC_AUTOTRADER_STATE_FILE:-$RUNTIME_ROOT/autotrader-btc-demo/state.json}"
PROVIDER_STATE_FILE="${AGENT_KRYPTO_PROVIDER_STATE_FILE:-$RUNTIME_ROOT/agent_krypto_provider_state}"

OKX_ALIAS="${OKX_AGENT_KRYPTO_ALIAS:-demo_main_full}"
AGENT_TIMEOUT_SECONDS="${AGENT_KRYPTO_TIMEOUT_SECONDS:-300}"

# cron uruchamia z minimalnym PATH (bez ~/.local/bin) — ścieżka pełna, żeby
# uniknąć "claude: No such file or directory" (exit 127) zaobserwowanego przy
# pierwszym realnym uruchomieniu z crontab.
CLAUDE_BIN="${CLAUDE_BIN:-/home/corozya/.local/bin/claude}"
CODEX_BIN="${CODEX_BIN:-/home/corozya/.local/bin/codex}"
CODEX_PROFILE="${AGENT_KRYPTO_CODEX_PROFILE:-crypto-trading-agent}"
CODEX_PROFILE_PATH="${AGENT_KRYPTO_CODEX_PROFILE_PATH:-${CODEX_HOME:-/home/corozya/.codex}/${CODEX_PROFILE}.config.toml}"
CODEX_SOURCE_PROFILE_PATH="${AGENT_KRYPTO_CODEX_SOURCE_PROFILE_PATH:-$REPO_ROOT/.codex/profiles/${CODEX_PROFILE}.config.toml}"
CODEX_AUTH_PATH="${AGENT_KRYPTO_CODEX_AUTH_PATH:-${CODEX_HOME:-/home/corozya/.codex}/auth.json}"
CODEX_INSTRUCTIONS_FILE="${AGENT_KRYPTO_CODEX_INSTRUCTIONS_FILE:-$REPO_ROOT/scripts/agent_krypto_codex_instructions.md}"

RUN_SLOT_EPOCH=$(( $(date -u +%s) / 900 * 900 ))
CYCLE_ID="agent-krypto-$(date -u -d "@$RUN_SLOT_EPOCH" +%Y%m%dT%H%M00Z)"
IDEMPOTENCY_KEY="$CYCLE_ID"
RUN_STARTED="$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)"

log() {
    printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)" "$1" | tee -a "$LOG_FILE"
}

cleanup_codex_runtime_home() {
    runtime_home="$1"
    case "$runtime_home" in
        "${TMPDIR:-/tmp}"/agent-krypto-codex-home.*)
            rm -rf -- "$runtime_home"
            ;;
        *)
            log "FATAL: odmowa czyszczenia nieoczekiwanej ścieżki Codex home: $runtime_home"
            return 1
            ;;
    esac
}

# Blokada obejmuje cały cykl. Drugi cron nie może równolegle pobrać danych,
# wybrać tego samego providera ani złożyć zlecenia na ten sam snapshot.
mkdir -p "$(dirname "$LOCK_FILE")"
exec 9>"$LOCK_FILE"
if ! flock -n 9; then
    log "ABORT: inny cykl agent-krypto nadal działa (lock=$LOCK_FILE)."
    exit 75
fi

# The adaptive BTC autotrader and this legacy cycle share demo_main_full.
# When the new runner is enabled, abort the legacy execution path so two
# independent agents cannot manage the same BTC account state.
if [ -r "$AUTOTRADER_STATE_FILE" ] && "$PYTHON" -c '
import json, sys
try:
    enabled = bool(json.load(open(sys.argv[1], encoding="utf-8")).get("enabled"))
except (OSError, ValueError, TypeError):
    enabled = True
raise SystemExit(0 if enabled else 1)
' "$AUTOTRADER_STATE_FILE"; then
    log "ABORT: autonomiczny BTC trader jest aktywny (state=$AUTOTRADER_STATE_FILE)."
    exit 75
fi

if [ "$PROVIDER" = "alternate" ]; then
    last_provider=""
    if [ -r "$PROVIDER_STATE_FILE" ]; then
        IFS= read -r last_provider < "$PROVIDER_STATE_FILE" || true
    fi
    if [ "$last_provider" = "claude" ]; then
        PROVIDER="codex"
    else
        PROVIDER="claude"
    fi
    provider_state_tmp="${PROVIDER_STATE_FILE}.$$"
    printf '%s\n' "$PROVIDER" > "$provider_state_tmp"
    mv "$provider_state_tmp" "$PROVIDER_STATE_FILE"
fi

# Preflight musi poprzedzać fetch/analyze. Brak CLI/profilu nie może zużyć
# świeżego snapshotu ani pozostawić wrażenia, że runda dotarła do decyzji.
if [ "$PROVIDER" = "claude" ]; then
    if [ ! -x "$CLAUDE_BIN" ]; then
        log "FATAL: Claude CLI nie istnieje lub nie jest wykonywalne: $CLAUDE_BIN"
        exit 1
    fi
    if [ ! -x "$PREFLIGHT_PYTHON" ]; then
        log "FATAL: Python do preflight MCP nie istnieje lub nie jest wykonywalny: $PREFLIGHT_PYTHON"
        exit 1
    fi
    if [ ! -r "$MCP_CONFIG" ]; then
        log "FATAL: brak runtime config MCP Claude: $MCP_CONFIG"
        exit 1
    fi
    mcp_preflight_output="$("$PREFLIGHT_PYTHON" "$MCP_CONFIG_VALIDATOR" "$MCP_CONFIG" 2>&1)"
    mcp_preflight_exit=$?
    if [ "$mcp_preflight_exit" -ne 0 ]; then
        log "FATAL: niepoprawny runtime config MCP Claude: $mcp_preflight_output"
        exit 1
    fi
else
    if [ ! -x "$CODEX_BIN" ]; then
        log "FATAL: Codex CLI nie istnieje lub nie jest wykonywalne: $CODEX_BIN"
        exit 1
    fi
    if [ ! -r "$CODEX_PROFILE_PATH" ]; then
        log "FATAL: profil Codexa '$CODEX_PROFILE' nie istnieje lub nie jest czytelny: $CODEX_PROFILE_PATH. Uruchom SAURON /onboarding i zainstaluj wygenerowany profil."
        exit 1
    fi
    if [ ! -r "$CODEX_SOURCE_PROFILE_PATH" ]; then
        log "FATAL: źródłowy profil Codexa '$CODEX_PROFILE' nie istnieje lub nie jest czytelny: $CODEX_SOURCE_PROFILE_PATH. Uruchom SAURON /onboarding."
        exit 1
    fi
    codex_profile_preflight_output="$("$PREFLIGHT_PYTHON" "$CODEX_PROFILE_VALIDATOR" "$CODEX_SOURCE_PROFILE_PATH" "$CODEX_PROFILE_PATH" approve 2>&1)"
    codex_profile_preflight_exit=$?
    if [ "$codex_profile_preflight_exit" -ne 0 ]; then
        log "FATAL: niepoprawny profil Codexa '$CODEX_PROFILE': $codex_profile_preflight_output"
        exit 1
    fi
    if [ ! -r "$CODEX_AUTH_PATH" ]; then
        log "FATAL: auth Codexa nie istnieje lub nie jest czytelny: $CODEX_AUTH_PATH"
        exit 1
    fi
    if [ ! -r "$CODEX_INSTRUCTIONS_FILE" ]; then
        log "FATAL: instrukcje roli agent-krypto dla Codexa nie istnieją lub nie są czytelne: $CODEX_INSTRUCTIONS_FILE"
        exit 1
    fi
    codex_developer_instructions_json="$("$PREFLIGHT_PYTHON" -c 'import json, pathlib, sys; print(json.dumps(pathlib.Path(sys.argv[1]).read_text()))' "$CODEX_INSTRUCTIONS_FILE" 2>&1)"
    codex_instructions_exit=$?
    if [ "$codex_instructions_exit" -ne 0 ]; then
        log "FATAL: nie udało się przygotować runtime instructions Codexa: $codex_developer_instructions_json"
        exit 1
    fi
fi

if [ ! -r "$REPORT_SCHEMA" ]; then
    log "FATAL: brak schematu raportu: $REPORT_SCHEMA"
    exit 1
fi

log "=== cycle start provider=$PROVIDER idempotency_key=$IDEMPOTENCY_KEY ==="

# -- krok 1: fetch (#78) -----------------------------------------------------
cd "$BACKEND" || { log "FATAL: cd $BACKEND nieudany"; exit 1; }

fetch_output="$("$PYTHON" scripts/fetch_crypto_market_data.py "$OKX_ALIAS" 2>&1)"
fetch_exit=$?
log "fetch exit=$fetch_exit"
printf '%s\n' "$fetch_output" | tee -a "$LOG_FILE"

if [ "$fetch_exit" -ne 0 ]; then
    log "ABORT: fetch nie zapisał danych dla żadnego symbolu — pomijam analyze/decision w tym cyklu."
    exit 1
fi

# -- krok 2: analiza (#79) ---------------------------------------------------
analyze_output="$("$PYTHON" scripts/analyze_crypto_market_data.py 2>&1)"
analyze_exit=$?
log "analyze exit=$analyze_exit"
printf '%s\n' "$analyze_output" | tee -a "$LOG_FILE"

if [ "$analyze_exit" -ne 0 ]; then
    log "ABORT: analiza nie wyprodukowała snapshotu dla żadnego symbolu — pomijam decision w tym cyklu."
    exit 1
fi

# Analyze może zakończyć się sukcesem, gdy powstał tylko jeden snapshot. Agent
# może wystartować dopiero po walidacji pełnego, świeżego kompletu trzech JSON.
market_snapshots="$("$PREFLIGHT_PYTHON" "$SNAPSHOT_PREPARER" \
    "$SNAPSHOT_DIR" "$SNAPSHOT_MAX_AGE_SECONDS" "$RUN_STARTED" 2>&1)"
snapshots_exit=$?
if [ "$snapshots_exit" -ne 0 ]; then
    log "ABORT: niepoprawny komplet snapshotów analizy — pomijam decision: $market_snapshots"
    exit 1
fi

# -- krok 2b: sync wartości konta z OKX (#87) --------------------------------
# Lokalny ledger transactions ma znany bug (qty źle skalowane, brak sync
# zamknięć SL/TP) — total_value/cash w get_portfolio muszą pochodzić z OKX,
# nie z ledgera. Brak świeżego salda jest fail-closed.
sync_output="$("$PYTHON" scripts/sync_krypto_portfolio_value.py 2>&1)"
sync_exit=$?
log "sync_krypto_portfolio_value exit=$sync_exit"
printf '%s\n' "$sync_output" | tee -a "$LOG_FILE"
if [ "$sync_exit" -ne 0 ]; then
    log "ABORT: sync wartości konta z OKX nieudany — pomijam decision."
    exit 1
fi

# -- krok 2c: otwarte pozycje z OKX (realny stan konta demo) ------------------
# get_portfolio (MCP) dla trading+okx portfeli pokazuje pozycje z lokalnego
# ledgera FIFO, nie z OKX — nadpisywany jest tylko total_value (patrz komentarz
# #87 przy is_trading_okx_exchange w services/game.py), qty/SL-TP sync w
# ledgerze mają znany bug. Brak autorytatywnego stanu jest fail-closed.
positions_output="$("$PYTHON" scripts/print_open_positions.py 2>&1)"
positions_exit=$?
log "print_open_positions exit=$positions_exit"
printf '%s\n' "$positions_output" | tee -a "$LOG_FILE"
if [ "$positions_exit" -ne 0 ]; then
    log "ABORT: brak autorytatywnego stanu pozycji OKX — pomijam decision."
    exit 1
fi

# -- krok 3: decyzja agenta (#80/#92, headless) ------------------------------
cd "$REPO_ROOT" || { log "FATAL: cd $REPO_ROOT nieudany"; exit 1; }

AGENT_PROMPT="/agent-krypto uruchom cykl decyzyjny. idempotency_key bazowy dla execute_trade w tym cyklu: ${IDEMPOTENCY_KEY} (dopisz sufiks per symbol/transakcję, np. ${IDEMPOTENCY_KEY}-BTC, żeby BTC i ETH miały odrębne klucze).

UWAGA — realny stan otwartych pozycji na OKX (konto demo), pobrany bezpośrednio przed tym promptem:
${positions_output}

get_portfolio (MCP) może pokazać INNE pozycje niż powyższe — dla tego portfela pole pozycji w get_portfolio pochodzi z lokalnego ledgera, który ma znany bug (qty źle skalowane, brak sync zamknięć SL/TP). Traktuj powyższy stan z OKX jako źródło prawdy o tym, co jest faktycznie otwarte."

AGENT_PROMPT="${AGENT_PROMPT}

ZWERYFIKOWANE SNAPSHOTY ANALIZY — źródło prawdy dla tej rundy. Nie szukaj ich przez shell/Read i nie twierdź, że ich brakuje. Każdy obiekt jest pełną zawartością pliku po analyze:
${market_snapshots}"

if [ "$INTERACTIVE" = true ]; then
    printf 'Dodatkowa instrukcja dla agenta (Enter = brak): ' >&2
    if ! IFS= read -r additional_question; then
        log "ABORT: nie udało się odczytać dodatkowego pytania ze stdin."
        exit 1
    fi

    if [ -n "$additional_question" ]; then
        AGENT_PROMPT="${AGENT_PROMPT}

DODATKOWA INSTRUKCJA UŻYTKOWNIKA:
${additional_question}"
    fi
fi

decision_started_ms="$(date +%s%3N)"
decision_cli_output=""

if [ "$PROVIDER" = "claude" ]; then
    IFS= read -r -d '' REPORT_SCHEMA_JSON < "$REPORT_SCHEMA" || true
    decision_output="$(timeout "$AGENT_TIMEOUT_SECONDS" "$CLAUDE_BIN" -p "$AGENT_PROMPT" \
        --mcp-config "$MCP_CONFIG" \
        --strict-mcp-config \
        --allowedTools \
            "mcp__portfolio-tracker__get_mandate" \
            "mcp__portfolio-tracker__get_portfolio" \
            "mcp__portfolio-tracker__size_okx_futures_entry" \
            "mcp__portfolio-tracker__execute_trade" \
            "mcp__portfolio-tracker__log_round" \
            "Read" \
        --permission-mode bypassPermissions \
        --json-schema "$REPORT_SCHEMA_JSON" \
        --output-format json \
        --add-dir "$REPO_ROOT" \
        2>&1)"
    decision_exit=$?
else
    codex_result_file="$(mktemp "${TMPDIR:-/tmp}/agent-krypto-codex.XXXXXX.json")"
    codex_runtime_home="$(mktemp -d "${TMPDIR:-/tmp}/agent-krypto-codex-home.XXXXXX")"
    chmod 700 "$codex_runtime_home"
    if ! cp "$CODEX_PROFILE_PATH" "$codex_runtime_home/${CODEX_PROFILE}.config.toml"; then
        log "FAIL: nie udało się przygotować izolowanego profilu Codexa."
        cleanup_codex_runtime_home "$codex_runtime_home"
        rm -f "$codex_result_file"
        exit 1
    fi
    # Auth pozostaje w prywatnym Codex home użytkownika. Tymczasowy runtime ma
    # tylko symlink; sekret nie jest kopiowany do repo ani do profilu.
    if ! ln -s "$CODEX_AUTH_PATH" "$codex_runtime_home/auth.json"; then
        log "FAIL: nie udało się podłączyć auth do izolowanego Codex home."
        cleanup_codex_runtime_home "$codex_runtime_home"
        rm -f "$codex_result_file"
        exit 1
    fi
    decision_cli_output="$(timeout "$AGENT_TIMEOUT_SECONDS" env CODEX_HOME="$codex_runtime_home" "$CODEX_BIN" exec \
        -C "$REPO_ROOT" \
        -p "$CODEX_PROFILE" \
        -c 'approval_policy="never"' \
        -c 'mcp_servers.portfolio-tracker.default_tools_approval_mode="approve"' \
        -c 'mcp_servers.portfolio-tracker.enabled_tools=["get_mandate","get_portfolio","size_okx_futures_entry","execute_trade","log_round"]' \
        -c "model_instructions_file=\"$CODEX_INSTRUCTIONS_FILE\"" \
        -c "developer_instructions=$codex_developer_instructions_json" \
        --sandbox read-only \
        --ephemeral \
        --output-schema "$REPORT_SCHEMA" \
        --output-last-message "$codex_result_file" \
        "$AGENT_PROMPT" \
        2>&1)"
    decision_exit=$?
    if [ -s "$codex_result_file" ]; then
        decision_output="$(< "$codex_result_file")"
    else
        decision_output="$decision_cli_output"
    fi
    rm -f "$codex_result_file"
    if ! cleanup_codex_runtime_home "$codex_runtime_home"; then
        log "FAIL: nie udało się usunąć izolowanego Codex home."
        exit 1
    fi
fi

decision_duration_ms=$(( $(date +%s%3N) - decision_started_ms ))
log "decision provider=$PROVIDER exit=$decision_exit duration_ms=$decision_duration_ms"
if [ -n "$decision_cli_output" ]; then
    printf '%s\n' "$decision_cli_output" | tee -a "$LOG_FILE"
fi
printf '%s\n' "$decision_output" | tee -a "$LOG_FILE"

# #83: wyciąga WAIT/TRADE per symbol z odpowiedzi agenta do osobnego,
# czytelnego JSONL — niezależnie od exit code (nawet przy błędzie/timeoucie
# chcemy zapisać co się dało, log_agent_krypto_decision.py sam obsługuje
# pusty/niepoprawny JSON na wejściu).
printf '%s' "$decision_output" | "$PYTHON" "$REPO_ROOT/scripts/log_agent_krypto_decision.py" \
    "$IDEMPOTENCY_KEY" "$PROVIDER" "$decision_duration_ms"

# Poprawny JSON Schema nie oznacza udanej rundy. Walidacja semantyczna jest
# celowo po zapisie JSONL: również nieudane raporty muszą zostać w audycie.
report_validation_output="$(printf '%s' "$decision_output" | "$PREFLIGHT_PYTHON" "$REPORT_VALIDATOR" "$PROVIDER" 2>&1)"
report_validation_exit=$?

if [ "$decision_exit" -eq 124 ]; then
    log "ABORT: agent decyzyjny przekroczył timeout ${AGENT_TIMEOUT_SECONDS}s — cykl przerwany, brak gwarancji stanu (sprawdź get_portfolio ręcznie przed kolejnym cyklem)."
    exit 1
elif [ "$decision_exit" -ne 0 ]; then
    log "FAIL: agent decyzyjny zakończył się błędem (exit=$decision_exit)."
    exit 1
elif [ "$report_validation_exit" -ne 0 ]; then
    log "FAIL: raport agenta nie potwierdza ukończonej rundy: $report_validation_output"
    exit 1
fi

log "=== cycle done provider=$PROVIDER idempotency_key=$IDEMPOTENCY_KEY ==="
exit 0
